![](https://blog.rescale.com/wp-content/uploads/2017/02/markblogtensorflow.png)
# An open-source software library for Machine Intelligence
# Developed by Googld Brain
## https://www.tensorflow.org/

## 流程：建立計算圖 --> 啟動Session開始tensor flow (張量運算)
### 0維張量：純量
### 1維張量：向量
### 2維張量：矩陣
### 3、4...維張量

![](https://www.tensorflow.org/images/tensors_flowing.gif)

# TensorFlow Math Ops
https://www.tensorflow.org/api_guides/python/math_ops

# ㄧ、基本運算

In [1]:
import tensorflow as tf

In [2]:
a = tf.constant(10)
b = tf.constant(5)
c = tf.Variable(b+3)
add = tf.add(a,b)
sub = tf.subtract(a,b)
mul = tf.multiply(a,b)
div = tf.div(a,b)

## Session start & close

In [3]:
sess = tf.Session()
sess.run(tf.global_variables_initializer()) # 初始化所有Variables
print('a:',sess.run(a))
print('b:',sess.run(b))
print('c:',sess.run(c))
print('a+b:',sess.run(add))
print('a-b:',sess.run(sub))
print('a*b:',sess.run(mul))
print('a/b:',sess.run(div))
sess.close()

a: 10
b: 5
c: 8
a+b: 15
a-b: 5
a*b: 50
a/b: 2


## with: 自動關閉 Session

In [4]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer()) # 初始化所有Variables
    print(sess.run(a))
    print(sess.run(b))
    print(sess.run(c))
    
    # 輸出計算圖至TensorBoard
    writer = tf.summary.FileWriter("log/", graph = sess.graph)

10
5
8


## TensorBoard: 視覺化計算圖

In [5]:
# 啟動TensorBoard
!tensorboard --logdir=log

TensorBoard 0.1.6 at http://pyda:6006 (Press CTRL+C to quit)
^C


# 二、placeholder: 在Session中input後運算

In [6]:
x = tf.placeholder(tf.int32)
y = tf.placeholder(tf.int32)

In [7]:
add = tf.add(x,y)
sub = tf.subtract(x,y)
mul = tf.multiply(x,y)
div = tf.div(x,y)

In [8]:
with tf.Session() as sess:
    print('x+y:',sess.run(add, feed_dict={x: 10, y: 2}))
    print('x-y:',sess.run(sub, feed_dict={x: 10, y: 2}))
    print('x*y:',sess.run(mul, feed_dict={x: 10, y: 2}))
    print('x/y:',sess.run(div, feed_dict={x: 10, y: 2}))

x+y: 12
x-y: 8
x*y: 20
x/y: 5


# 三、矩陣運算

In [9]:
matrix1 = tf.constant([[3., 3.],[4., 4.],[5., 5.]])
matrix1

<tf.Tensor 'Const_2:0' shape=(3, 2) dtype=float32>

In [10]:
matrix2 = tf.constant([[2.],[1.]])
matrix2

<tf.Tensor 'Const_3:0' shape=(2, 1) dtype=float32>

In [11]:
product = tf.matmul(matrix1, matrix2)

In [12]:
with tf.Session() as sess:
    print('matrix1\n',sess.run(matrix1))
    print('matrix2\n',sess.run(matrix2))
    print('product\n',sess.run(product))

matrix1
 [[ 3.  3.]
 [ 4.  4.]
 [ 5.  5.]]
matrix2
 [[ 2.]
 [ 1.]]
product
 [[  9.]
 [ 12.]
 [ 15.]]
